# Generated by Django 6.0.3 on 2026-04-03 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('short_name', models.CharField(default='UNKNOWN', max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('description', models.TextField(default='')),
                ('state', models.CharField(default='Unknown', max_length=100)),
                ('city', models.CharField(default='Unknown', max_length=100)),
                ('website', models.URLField(blank=True, default='https://example.com')),
                ('type', models.CharField(choices=[('Government', 'Government'), ('Private', 'Private'), ('Autonomous', 'Autonomous')], default='Government', max_length=50)),
                ('tier', models.CharField(choices=[('IIT', 'IIT - Premier'), ('NIT', 'NIT - National'), ('IIIT', 'IIIT - IT-Focused'), ('Govt College', 'Government College'), ('Autonomous', 'Autonomous Institution'), ('Tier-1 Premium', 'Tier-1 Premium Private'), ('Tier-2 Professional', 'Tier-2 Professional'), ('Tier-3 Regional', 'Tier-3 Regional'), ('Tier-4 District', 'Tier-4 District Level'), ('Regular', 'Regular')], default='Regular', max_length=50)),
                ('established', models.IntegerField(default=2000)),
                ('accreditation', models.CharField(default='Not Specified', max_length=200)),
                ('placement_percentage', models.FloatField(default=0)),
                ('average_package_lpa', models.FloatField(default=0)),
                ('highest_package_lpa', models.FloatField(default=0)),
                ('fees_per_semester_lakhs', models.FloatField(default=0)),
                ('nirf_rank', models.IntegerField(default=999)),
                ('total_students', models.IntegerField(default=0)),
                ('faculty_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'ordering': ['-nirf_rank'],
                'indexes': [models.Index(fields=['state'], name='colleges_co_state_06f392_idx'), models.Index(fields=['type'], name='colleges_co_type_8c51b3_idx'), models.Index(fields=['tier'], name='colleges_co_tier_97fb1c_idx'), models.Index(fields=['placement_percentage'], name='colleges_co_placeme_b48b04_idx')],
            },
        ),
        migrations.CreateModel(
            name='CollegeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(default='CSE', max_length=20)),
                ('cutoff', models.FloatField(default=0)),
                ('fees', models.IntegerField(default=0)),
                ('fees_per_year_lakhs', models.FloatField(default=0)),
                ('placement_percentage', models.IntegerField(default=0)),
                ('duration_years', models.IntegerField(default=4)),
                ('seats', models.IntegerField(default=60)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.college')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
