# Generated by Django 6.0.3 on 2026-04-03 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpdateTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('records_updated', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_sources', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Data Update Tracker',
                'verbose_name_plural': 'Data Update Trackers',
            },
        ),
    ]
