# Generated by Django 6.0.3 on 2026-04-14 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0002_dataupdatetracker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='accreditation',
        ),
        migrations.RemoveField(
            model_name='college',
            name='average_package_lpa',
        ),
        migrations.RemoveField(
            model_name='college',
            name='faculty_count',
        ),
        migrations.RemoveField(
            model_name='college',
            name='highest_package_lpa',
        ),
        migrations.RemoveField(
            model_name='college',
            name='short_name',
        ),
        migrations.RemoveField(
            model_name='college',
            name='total_students',
        ),
        migrations.RemoveField(
            model_name='course',
            name='seats',
        ),
    ]
