# Generated by Django 5.0.6 on 2026-04-17 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0004_add_stream_and_degree_level'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='course',
            new_name='colleges_co_stream_3773b8_idx',
            old_name='colleges_co_stream_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='colleges_co_code_558feb_idx',
            old_name='colleges_co_code_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='colleges_co_degree__985392_idx',
            old_name='colleges_co_degree_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='colleges_co_is_vali_1ca197_idx',
            old_name='colleges_co_valid_idx',
        ),
        migrations.AddField(
            model_name='college',
            name='image_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default='UNKNOWN', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
