# Generated by Django 5.0.6 on 2026-04-18 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0005_rename_colleges_co_stream_idx_colleges_co_stream_3773b8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='established',
        ),
        migrations.RemoveField(
            model_name='college',
            name='university_name',
        ),
    ]
