# Generated by Django 5.0.6 on 2026-04-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0006_remove_college_established_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='colleges_co_code_558feb_idx',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='course',
            name='placement_percentage',
        ),
    ]
