# Generated by Django 5.0.6 on 2026-04-18 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0007_remove_course_colleges_co_code_558feb_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='fees_per_semester_lakhs',
        ),
    ]
