# Generated by Django 5.0.6 on 2026-04-19 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0008_remove_college_fees_per_semester_lakhs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataupdatetracker',
            options={},
        ),
        migrations.RemoveField(
            model_name='dataupdatetracker',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='dataupdatetracker',
            name='status',
        ),
        migrations.RemoveField(
            model_name='dataupdatetracker',
            name='total_sources',
        ),
        migrations.CreateModel(
            name='RealCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(default='Tamil Nadu', max_length=100)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('website', models.URLField(blank=True, default='')),
                ('collegedunia_url', models.URLField(blank=True, default='')),
                ('degree_level', models.CharField(choices=[('ENGINEERING', 'Engineering (B.Tech, B.E, M.Tech, etc)'), ('ARTS_SCIENCE', 'Arts & Science (B.Sc, B.A, M.Sc, etc)'), ('COMMERCE', 'Commerce (B.Com, MBA, M.Com, etc)'), ('LAW', 'Law (LLB, LLM, etc)'), ('MEDICAL', 'Medical (MBBS, BDS, etc)'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_validated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['city'], name='colleges_re_city_33e805_idx'), models.Index(fields=['state'], name='colleges_re_state_7d657c_idx'), models.Index(fields=['degree_level'], name='colleges_re_degree__d8bc49_idx')],
            },
        ),
        migrations.CreateModel(
            name='RealCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('stream', models.CharField(choices=[('ENGINEERING', 'Engineering'), ('ARTS_SCIENCE', 'Arts & Science'), ('COMMERCE', 'Commerce'), ('LAW', 'Law'), ('MEDICAL', 'Medical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=30)),
                ('degree_type', models.CharField(default='Unknown', max_length=50)),
                ('fees_lakhs', models.FloatField(default=0)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('RUNNING', 'Running')], default='RUNNING', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_sources', models.IntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='colleges.realcollege')),
            ],
            options={
                'verbose_name': 'Data Update Tracker',
                'verbose_name_plural': 'Data Update Trackers',
            },
        ),
    ]
