# Generated by Django 5.0.6 on 2026-04-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0003_remove_old_models'),
        ('colleges', '0009_alter_dataupdatetracker_options_and_more'),
    ]

    operations = [
    ]
