"""
Serializers for Student Authentication and Profile Management
"""

from rest_framework import serializers
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from students.models import StudentProfile


class StudentProfileSerializer(serializers.ModelSerializer):
    """Serializer for StudentProfile"""
    username = serializers.CharField(source='user.username', read_only=True)
    email = serializers.EmailField(source='user.email', read_only=True)
    first_name = serializers.CharField(source='user.first_name', read_only=True)
    last_name = serializers.CharField(source='user.last_name', read_only=True)
    
    class Meta:
        model = StudentProfile
        fields = [
            'id', 'username', 'email', 'first_name', 'last_name', 'phone',
            'education_level', 'course_type', 'group', 'cutoff_marks',
            'preferred_location', 'budget', 'hostel_required', 'created_at', 'updated_at'
        ]
        read_only_fields = ['id', 'created_at', 'updated_at']


class UserSerializer(serializers.ModelSerializer):
    """Serializer for User model"""
    class Meta:
        model = User
        fields = ['id', 'username', 'email', 'first_name', 'last_name']
        read_only_fields = ['id']


class RegisterSerializer(serializers.ModelSerializer):
    """Registration serializer"""
    password = serializers.CharField(write_only=True, min_length=6)
    password2 = serializers.CharField(write_only=True, min_length=6)
    email = serializers.EmailField()
    first_name = serializers.CharField(required=False, allow_blank=True)
    last_name = serializers.CharField(required=False, allow_blank=True)
    username = serializers.CharField(required=False, read_only=True)
    
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name', 'password', 'password2']
    
    def validate(self, attrs):
        """Validate passwords match"""
        if attrs['password'] != attrs['password2']:
            raise serializers.ValidationError({
                'password': 'Passwords do not match'
            })
        return attrs
    
    def validate_email(self, value):
        """Check if email already exists"""
        if User.objects.filter(email=value).exists():
            raise serializers.ValidationError("Email already registered")
        return value
    
    def create(self, validated_data):
        """Create user and profile with autogenerated username from email"""
        validated_data.pop('password2')
        password = validated_data.pop('password')
        email = validated_data.get('email')
        
        # Auto-generate username from email (e.g., user@example.com -> user_1)
        base_username = email.split('@')[0].replace('+', '_').replace('.', '_')[:25]
        username = base_username
        counter = 1
        
        # Make username unique if it exists
        while User.objects.filter(username=username).exists():
            username = f"{base_username}_{counter}"
            counter += 1
        
        validated_data['username'] = username
        user = User.objects.create_user(**validated_data)
        user.set_password(password)
        user.save()
        
        # Create StudentProfile
        StudentProfile.objects.create(user=user)
        
        return user


class LoginSerializer(serializers.Serializer):
    """Login serializer - accepts email or username"""
    email = serializers.CharField()
    password = serializers.CharField(write_only=True)
    
    def validate(self, attrs):
        """Authenticate user by email or username"""
        email_or_username = attrs.get('email')
        password = attrs.get('password')
        
        # Try to authenticate with email first
        try:
            user_obj = User.objects.get(email=email_or_username)
            user = authenticate(username=user_obj.username, password=password)
        except User.DoesNotExist:
            # Fall back to username
            user = authenticate(username=email_or_username, password=password)
        
        if not user:
            raise serializers.ValidationError(
                "Invalid email or password"
            )
        
        attrs['user'] = user
        return attrs


class LogoutSerializer(serializers.Serializer):
    """Logout serializer (empty for now)"""
    pass


class ChangePasswordSerializer(serializers.Serializer):
    """Change password serializer"""
    old_password = serializers.CharField(write_only=True)
    new_password = serializers.CharField(write_only=True, min_length=6)
    new_password2 = serializers.CharField(write_only=True, min_length=6)
    
    def validate(self, attrs):
        if attrs['new_password'] != attrs['new_password2']:
            raise serializers.ValidationError({
                'new_password': 'New passwords do not match'
            })
        return attrs
